In [1]:
import sys
from pathlib import Path

# Add the project root folder to Python's path
project_root = Path().resolve().parent
sys.path.insert(0, str(project_root))

In [2]:
from src.data.loader import load_session

In [3]:
session = load_session(
    2026,
    "Monaco",
    "R"
)

core           INFO 	Loading data for Monaco Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '44', '10', '6', '81', '30', '41', '23', '31', '14', '5', '63', '27', '43', '11', '55', '16', '18', '1', '87', '77', '3']

In [4]:
print(session)

2026 Season Round 6: Monaco Grand Prix - Race

In [5]:
session.results.head()

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
12,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,1.0,1,1.0,NaT,NaT,NaT,0 days 02:23:31.243000,Finished,25.0,78.0
44,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,2.0,2,3.0,NaT,NaT,NaT,0 days 00:00:06.271000,Finished,18.0,78.0
10,10,P GASLY,GAS,gasly,Alpine,00A1E8,alpine,Pierre,Gasly,Pierre Gasly,...,3.0,3,9.0,NaT,NaT,NaT,0 days 00:00:20.369000,Finished,15.0,78.0
6,6,I HADJAR,HAD,hadjar,Red Bull Racing,4781D7,red_bull,Isack,Hadjar,Isack Hadjar,...,4.0,4,5.0,NaT,NaT,NaT,0 days 00:00:23.394000,Finished,12.0,78.0
81,81,O PIASTRI,PIA,piastri,McLaren,F47600,mclaren,Oscar,Piastri,Oscar Piastri,...,5.0,5,7.0,NaT,NaT,NaT,0 days 00:00:24.261000,Finished,10.0,78.0

In [6]:
session.laps.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:56:50.495000,NOR,1,0 days 00:01:30.629000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:39.379000,...,True,McLaren,0 days 00:55:19.645000,2026-06-07 13:03:11.904,12,8.0,False,,False,False
1,0 days 00:58:11.179000,NOR,1,0 days 00:01:20.684000,2.0,1.0,NaT,NaT,0 days 00:00:21.738000,0 days 00:00:37.534000,...,True,McLaren,0 days 00:56:50.495000,2026-06-07 13:04:42.754,1,8.0,False,,False,True
2,0 days 00:59:31.374000,NOR,1,0 days 00:01:20.195000,3.0,1.0,NaT,NaT,0 days 00:00:21.482000,0 days 00:00:37.614000,...,True,McLaren,0 days 00:58:11.179000,2026-06-07 13:06:03.438,1,8.0,False,,False,True
3,0 days 01:00:50.865000,NOR,1,0 days 00:01:19.491000,4.0,1.0,NaT,NaT,0 days 00:00:21.206000,0 days 00:00:37.169000,...,True,McLaren,0 days 00:59:31.374000,2026-06-07 13:07:23.633,1,8.0,False,,False,True
4,0 days 01:02:09.853000,NOR,1,0 days 00:01:18.988000,5.0,1.0,NaT,NaT,0 days 00:00:20.871000,0 days 00:00:36.960000,...,True,McLaren,0 days 01:00:50.865000,2026-06-07 13:08:43.124,1,8.0,False,,False,True

In [7]:
session.weather_data.head()

,Time,AirTemp,Humidity,Pressure,Rainfall,TrackTemp,WindDirection,WindSpeed
0,0 days 00:00:24.792000,23.3,64.7,1022.1,False,33.1,244,0.5
1,0 days 00:01:24.809000,23.4,64.1,1022.0,False,34.0,0,0.0
2,0 days 00:02:24.794000,23.0,64.1,1022.0,False,34.0,0,0.0
3,0 days 00:03:24.789000,23.3,63.5,1022.1,False,34.4,0,0.0
4,0 days 00:04:24.791000,23.5,63.7,1022.1,False,35.1,131,0.5

In [8]:
session.laps.columns

Index(['Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber', 'Stint',
       'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time',
       'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime',
       'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST', 'IsPersonalBest',
       'Compound', 'TyreLife', 'FreshTyre', 'Team', 'LapStartTime',
       'LapStartDate', 'TrackStatus', 'Position', 'Deleted', 'DeletedReason',
       'FastF1Generated', 'IsAccurate'],
      dtype='object')