In [1]:
import sys
from pathlib import Path

project_root = Path().resolve().parent
sys.path.insert(0, str(project_root))

In [2]:
from src.data.loader import load_session
from src.analytics.strategy_analysis import stint_analysis

session = load_session(2024, "Monaco", "R")

core           INFO 	Loading data for Monaco Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '81', '55', '4', '63', '1', '44', '22', '23', '10', '14', '3', '77', '18', '2', '24', '31', '11', '27', '20']

In [3]:
stints = stint_analysis(session)

stints

,Driver,Team,Stint,Compound,Start Lap,End Lap,Stint Length,Average Lap Time (s),Fastest Lap (s)
0,ALB,Williams,2.0,HARD,2.0,77.0,76,80.984,77.060
1,ALO,Aston Martin,2.0,MEDIUM,2.0,76.0,75,81.150,77.939
2,BOT,Kick Sauber,2.0,MEDIUM,2.0,15.0,14,86.305,81.221
3,BOT,Kick Sauber,3.0,HARD,16.0,76.0,61,79.836,76.561
4,GAS,Alpine,2.0,MEDIUM,2.0,77.0,76,81.028,75.625
5,HAM,Mercedes,2.0,MEDIUM,3.0,51.0,49,80.136,77.398
6,HAM,Mercedes,3.0,HARD,52.0,78.0,27,75.822,74.165
7,LEC,Ferrari,2.0,HARD,3.0,78.0,76,78.439,75.162
8,NOR,McLaren,2.0,HARD,3.0,78.0,76,78.533,75.742
9,PIA,McLaren,2.0,HARD,3.0,78.0,76,78.524,76.281
10,RIC,RB,2.0,HARD,2.0,76.0,75,81.229,77.172
11,RUS,Mercedes,2.0,MEDIUM,3.0,78.0,76,78.590,75.228
12,SAI,Ferrari,2.0,HARD,3.0,78.0,76,78.523,74.726
13,SAR,Williams,2.0,HARD,2.0,57.0,56,82.493,79.511
14,SAR,Williams,3.0,MEDIUM,58.0,76.0,19,77.268,75.525
15,STR,Aston Martin,2.0,MEDIUM,2.0,42.0,41,82.825,79.016
16,STR,Aston Martin,3.0,HARD,43.0,48.0,6,84.270,78.062
17,STR,Aston Martin,4.0,SOFT,49.0,76.0,28,78.480,76.710
18,TSU,RB,2.0,HARD,2.0,77.0,76,80.874,74.720
19,VER,Red Bull Racing,2.0,MEDIUM,3.0,52.0,50,80.045,78.074
20,VER,Red Bull Racing,3.0,HARD,53.0,78.0,26,75.798,74.569
21,ZHO,Kick Sauber,2.0,HARD,2.0,70.0,69,81.900,77.936
22,ZHO,Kick Sauber,3.0,SOFT,71.0,76.0,6,78.913,74.718

In [4]:
from importlib import reload
import src.analytics.strategy_analysis as sa

reload(sa)

In [5]:
pace = sa.race_pace_evolution(session)

pace

,Driver,Team,Lap Number,Compound,Tyre Life,Stint,Position,Lap Time (s)
0,ALB,Williams,1.0,MEDIUM,1.0,1.0,9.0,2494.817
1,ALB,Williams,2.0,HARD,1.0,2.0,9.0,142.255
2,ALB,Williams,3.0,HARD,2.0,2.0,9.0,87.834
3,ALB,Williams,4.0,HARD,3.0,2.0,9.0,83.286
4,ALB,Williams,5.0,HARD,4.0,2.0,9.0,83.369
...,...,...,...,...,...,...,...,...
1221,ZHO,Kick Sauber,72.0,SOFT,2.0,3.0,16.0,80.585
1222,ZHO,Kick Sauber,73.0,SOFT,3.0,3.0,16.0,75.233
1223,ZHO,Kick Sauber,74.0,SOFT,4.0,3.0,16.0,80.473
1224,ZHO,Kick Sauber,75.0,SOFT,5.0,3.0,16.0,74.718
1225,ZHO,Kick Sauber,76.0,SOFT,6.0,3.0,16.0,77.173

In [6]:
import src.analytics.strategy_analysis as sa

reload(sa)

In [7]:
compound = sa.compound_comparison(session)

compound

,Compound,Average Lap Time (s),Fastest Lap (s),Average Tyre Life,Maximum Tyre Life,Number of Laps,Drivers Using Compound
0,SOFT,78.556,74.718,12.559,28.0,34,2
1,HARD,79.798,74.165,35.885,78.0,776,13
2,MEDIUM,80.546,75.228,31.622,77.0,400,8